<a href="https://colab.research.google.com/github/katerinaSo/numpyBasics02/blob/main/numpyBasics01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy Array

In [1]:
import numpy as np

In [2]:
a=[1,2,3]
type(a)

list

In [4]:
aa=np.array(a)
aa

array([1, 2, 3])

In [5]:
type(aa)

numpy.ndarray

In [9]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(0,101,5)

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100])

In [15]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.ones((5,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [35]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [37]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [38]:
np.random.rand(3)

array([0.10862135, 0.26386404, 0.08223432])

In [39]:
np.random.rand(2,3)

array([[0.9513763 , 0.14657186, 0.87831275],
       [0.25518337, 0.24510325, 0.33021619]])

In [40]:
np.random.randn(4,3)

array([[ 0.99194385,  1.79926911,  0.16909175],
       [ 0.1159424 , -2.03660926, -1.96374097],
       [-0.49790648, -0.68785347, -0.10650652],
       [-1.39683383,  0.10847983, -1.32682921]])

In [73]:
np.random.randint(1,11,3)

array([3, 7, 9])

In [80]:
a=np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [82]:
a.reshape(10,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

In [88]:
a.reshape(4,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [89]:
a.reshape(2,10)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [90]:
a.argmax() # index number

19

In [92]:
a.max()

20

In [93]:
a.argmin()

0

In [94]:
a.min()

1

In [97]:
c=a.reshape( 4,5)
c

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [98]:
c.shape

(4, 5)

In [99]:
c.dtype

dtype('int64')

In [100]:
c[3]

array([16, 17, 18, 19, 20])

In [101]:
c[1,4]

10

In [104]:
c[:,2:4]

array([[ 3,  4],
       [ 8,  9],
       [13, 14],
       [18, 19]])

In [107]:
c[2:4]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [109]:
c[:2]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [110]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [113]:
a[1:6]=500.6
a

array([  1, 500, 500, 500, 500, 500,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

In [116]:
b=a[2:7] # nothing new created, only view
b

array([500, 500, 500, 500,   7])

In [117]:
b[:]=0
b

array([0, 0, 0, 0, 0])

In [118]:
a

array([  1, 500,   0,   0,   0,   0,   0,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

In [119]:
b=a.copy() # copied to a new variable

In [120]:
b

array([  1, 500,   0,   0,   0,   0,   0,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

In [121]:
b[3:6]=300
b

array([  1, 500,   0, 300, 300, 300,   0,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

In [122]:
a

array([  1, 500,   0,   0,   0,   0,   0,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

In [123]:
d=np.array([[1,2,4],[6,4,8]])
d

array([[1, 2, 4],
       [6, 4, 8]])

In [124]:
d[0,0]

1

In [125]:
d[0,1]

2

In [126]:
d[0][2]

4

In [127]:
d[-1,-1]

8