<a href="https://colab.research.google.com/github/katerinaSo/numpyBasics02/blob/main/numpyBasics01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy Array

In [1]:
import numpy as np

In [2]:
a=[1,2,3]
type(a)

list

In [4]:
aa=np.array(a)
aa

array([1, 2, 3])

In [5]:
type(aa)

numpy.ndarray

In [9]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(0,101,5)

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100])

In [15]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.ones((5,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [35]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [37]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [38]:
np.random.rand(3)

array([0.10862135, 0.26386404, 0.08223432])

In [39]:
np.random.rand(2,3)

array([[0.9513763 , 0.14657186, 0.87831275],
       [0.25518337, 0.24510325, 0.33021619]])

In [40]:
np.random.randn(4,3)

array([[ 0.99194385,  1.79926911,  0.16909175],
       [ 0.1159424 , -2.03660926, -1.96374097],
       [-0.49790648, -0.68785347, -0.10650652],
       [-1.39683383,  0.10847983, -1.32682921]])

In [73]:
np.random.randint(1,11,3)

array([3, 7, 9])

In [80]:
a=np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [82]:
a.reshape(10,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

In [88]:
a.reshape(4,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [89]:
a.reshape(2,10)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [90]:
a.argmax() # index number

19

In [92]:
a.max()

20

In [93]:
a.argmin()

0

In [94]:
a.min()

1

In [97]:
c=a.reshape( 4,5)
c

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [98]:
c.shape

(4, 5)

In [99]:
c.dtype

dtype('int64')

In [100]:
c[3]

array([16, 17, 18, 19, 20])

In [101]:
c[1,4]

10

In [104]:
c[:,2:4]

array([[ 3,  4],
       [ 8,  9],
       [13, 14],
       [18, 19]])

In [107]:
c[2:4]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [109]:
c[:2]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [110]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [113]:
a[1:6]=500.6
a

array([  1, 500, 500, 500, 500, 500,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

In [116]:
b=a[2:7] # nothing new created, only view
b

array([500, 500, 500, 500,   7])

In [117]:
b[:]=0
b

array([0, 0, 0, 0, 0])

In [118]:
a

array([  1, 500,   0,   0,   0,   0,   0,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

In [119]:
b=a.copy() # copied to a new variable

In [120]:
b

array([  1, 500,   0,   0,   0,   0,   0,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

In [121]:
b[3:6]=300
b

array([  1, 500,   0, 300, 300, 300,   0,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

In [122]:
a

array([  1, 500,   0,   0,   0,   0,   0,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

In [123]:
d=np.array([[1,2,4],[6,4,8]])
d

array([[1, 2, 4],
       [6, 4, 8]])

In [124]:
d[0,0]

1

In [125]:
d[0,1]

2

In [126]:
d[0][2]

4

In [127]:
d[-1,-1]

8

In [129]:
d[:2,-2:]

array([[2, 4],
       [4, 8]])

**conditional indexing**

In [131]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [134]:
b=a>2
b

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [135]:
a[b]

array([3, 4, 5, 6, 7, 8, 9])

In [136]:
a[a>3]

array([4, 5, 6, 7, 8, 9])

**Math operations**

In [137]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [138]:
a+a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [139]:
a-a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [140]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [141]:
a*a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [143]:
a*5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [145]:
a/a # nan for /0

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

**numpy operations**

In [146]:
np.sqrt(a)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [147]:
np.exp(a)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [148]:
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [149]:
np.log(a)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

[ufunc](https://numpy.org/doc/stable/reference/ufuncs.html)